Return to start() function when check_ssh_target failed
In old code, kdumpctl program exit directly when check_ssh_target failed
without printing "Starting kdump: FAILED". Then when manually invoke
"kdumpctl restart", only print "Stopping kdump: OK", but no "Starting
kdump: FAILED". That is unreasonable.

In this patch change check_ssh_target() to return when it failed. Then
check the returned value in start() function and print status if the
returned value is not 0.

Meanwhile change "space" to "tab" in function check_ssh_target(), make
those be consistent with the whole script file.

Signed-off-by: Baoquan He <bhe@redhat.com>
Acked-by: Dave Young <dyoung@redhat.com>

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -237,13 +237,14 @@ function check_ssh_config()
 
 function check_ssh_target()
 {
-    local _ret
-    ssh -q -i $SSH_KEY_LOCATION -o BatchMode=yes $DUMP_TARGET mkdir -p $SAVE_PATH
-    _ret=$?
-    if [ $_ret -ne 0 ]; then
-        echo "Could not create $DUMP_TARGET:$SAVE_PATH, you probably need to run \"kdumpctl propagate\""
-        exit $_ret
-    fi
+	local _ret
+	ssh -q -i $SSH_KEY_LOCATION -o BatchMode=yes $DUMP_TARGET mkdir -p $SAVE_PATH
+	_ret=$?
+	if [ $_ret -ne 0 ]; then
+		echo "Could not create $DUMP_TARGET:$SAVE_PATH, you probably need to run \"kdumpctl propagate\""  >&2
+		return 1
+	fi
+	return 0
 }
 
 function propagate_ssh_key()
@@ -371,7 +372,13 @@ function start()
 		fi
 	fi
 
-        check_ssh_config && check_ssh_target
+	if check_ssh_config; then
+		if ! check_ssh_target; then
+			echo "Starting kdump: [FAILED]"
+			return 1
+		fi
+	fi
+
 
 	check_config
 	if [ $? != 0 ]; then
