bash scripts: fix redundant exit code check
As suggested by:
https://github.com/koalaman/shellcheck/wiki/SC2181

Signed-off-by: Kairui Song <kasong@redhat.com>
Acked-by: Philipp Rudo <prudo@redhat.com>

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -37,8 +37,7 @@ fi
 . /lib/kdump/kdump-logger.sh
 
 #initiate the kdump logger
-dlog_init
-if [[ $? -ne 0 ]]; then
+if ! dlog_init; then
 	echo "failed to initiate the kdump logger."
 	exit 1
 fi
@@ -47,8 +46,7 @@ single_instance_lock()
 {
 	local rc timeout=5
 
-	exec 9>/var/lock/kdump
-	if [[ $? -ne 0 ]]; then
+	if ! exec 9>/var/lock/kdump; then
 		derror "Create file lock failed"
 		exit 1
 	fi
@@ -80,8 +78,7 @@ save_core()
 
 	mkdir -p "$coredir"
 	ddebug "cp --sparse=always /proc/vmcore $coredir/vmcore-incomplete"
-	cp --sparse=always /proc/vmcore "$coredir/vmcore-incomplete"
-	if [[ $? == 0 ]]; then
+	if cp --sparse=always /proc/vmcore "$coredir/vmcore-incomplete"; then
 		mv "$coredir/vmcore-incomplete" "$coredir/vmcore"
 		dinfo "saved a vmcore to $coredir"
 	else
@@ -95,8 +92,7 @@ save_core()
 		ddebug "makedumpfile --dump-dmesg $coredir/vmcore $coredir/dmesg"
 		makedumpfile --dump-dmesg "$coredir/vmcore" "$coredir/dmesg" >/dev/null 2>&1
 		ddebug "dumpoops -d $coredir/dmesg"
-		dumpoops -d "$coredir/dmesg" >/dev/null 2>&1
-		if [[ $? == 0 ]]; then
+		if dumpoops -d "$coredir/dmesg" >/dev/null 2>&1; then
 			dinfo "kernel oops has been collected by abrt tool"
 		fi
 	fi
@@ -121,8 +117,7 @@ check_earlykdump_is_enabled()
 rebuild_kdump_initrd()
 {
 	ddebug "rebuild kdump initrd: $MKDUMPRD $TARGET_INITRD $KDUMP_KERNELVER"
-	$MKDUMPRD "$TARGET_INITRD" "$KDUMP_KERNELVER"
-	if [[ $? != 0 ]]; then
+	if ! $MKDUMPRD "$TARGET_INITRD" "$KDUMP_KERNELVER"; then
 		derror "mkdumprd: failed to make kdump initrd"
 		return 1
 	fi
@@ -184,8 +179,7 @@ backup_default_initrd()
 		dinfo "Backing up $DEFAULT_INITRD before rebuild."
 		# save checksum to verify before restoring
 		sha1sum "$DEFAULT_INITRD" > "$INITRD_CHECKSUM_LOCATION"
-		cp "$DEFAULT_INITRD" "$DEFAULT_INITRD_BAK"
-		if [[ $? -ne 0 ]]; then
+		if ! cp "$DEFAULT_INITRD" "$DEFAULT_INITRD_BAK"; then
 			dwarn "WARNING: failed to backup $DEFAULT_INITRD."
 			rm -f "$DEFAULT_INITRD_BAK"
 		fi
@@ -210,8 +204,7 @@ restore_default_initrd()
 			dwarn "WARNING: checksum mismatch! Can't restore original initrd.."
 		else
 			rm -f $INITRD_CHECKSUM_LOCATION
-			mv "$DEFAULT_INITRD_BAK" "$DEFAULT_INITRD"
-			if [[ $? -eq 0 ]]; then
+			if mv "$DEFAULT_INITRD_BAK" "$DEFAULT_INITRD"; then
 				derror "Restoring original initrd as fadump mode is disabled."
 				sync
 			fi
@@ -308,8 +301,7 @@ get_pcs_cluster_modified_files()
 
 setup_initrd()
 {
-	prepare_kdump_bootinfo
-	if [[ $? -ne 0 ]]; then
+	if ! prepare_kdump_bootinfo; then
 		derror "failed to prepare for kdump bootinfo."
 		return 1
 	fi
@@ -372,8 +364,7 @@ check_files_modified()
 			files="$files /lib/modules/$KDUMP_KERNELVER/modules.dep"
 		fi
 		for _module in $EXTRA_MODULES; do
-			_module_file="$(modinfo --set-version "$KDUMP_KERNELVER" --filename "$_module" 2>/dev/null)"
-			if [[ $? -eq 0 ]]; then
+			if _module_file="$(modinfo --set-version "$KDUMP_KERNELVER" --filename "$_module" 2>/dev/null)"; then
 				files="$files $_module_file"
 				for _dep_modules in $(modinfo -F depends "$_module" | tr ',' ' '); do
 				    files="$files $(modinfo --set-version "$KDUMP_KERNELVER" --filename "$_dep_modules" 2>/dev/null)"
@@ -389,8 +380,7 @@ check_files_modified()
 
 	# HOOKS is mandatory and need to check the modification time
 	files="$files $HOOKS"
-	check_exist "$files" && check_executable "$EXTRA_BINS"
-	[[ $? -ne 0 ]] && return 2
+	check_exist "$files" && check_executable "$EXTRA_BINS" || return 2
 
 	for file in $files; do
 		if [[ -e "$file" ]]; then
@@ -455,7 +445,7 @@ check_drivers_modified()
 		# Skip deprecated/invalid driver name or built-in module
 		_module_name=$(modinfo --set-version "$KDUMP_KERNELVER" -F name "$_driver" 2>/dev/null)
 		_module_filename=$(modinfo --set-version "$KDUMP_KERNELVER" -n "$_driver" 2>/dev/null)
-		if [[ $? -ne 0 ]] || [[ -z "$_module_name" ]] || [[ "$_module_filename" = *"(builtin)"* ]]; then
+		if [[ -z "$_module_name" ]] || [[ -z "$_module_filename" ]] || [[ "$_module_filename" = *"(builtin)"* ]]; then
 			continue
 		fi
 		if ! [[ " $_old_drivers " == *" $_module_name "* ]]; then
@@ -505,8 +495,7 @@ check_fs_modified()
 
 	# if --mount argument present then match old and new target, mount
 	# point and file system. If any of them mismatches then rebuild
-	echo "$_dracut_args" | grep -q "\-\-mount"
-	if [[ $? -eq 0 ]];then
+	if echo "$_dracut_args" | grep -q "\-\-mount"; then
 		# shellcheck disable=SC2046
 		set -- $(echo "$_dracut_args" | awk -F "--mount '" '{print $2}' | cut -d' ' -f1,2,3)
 		_old_dev=$1
@@ -558,11 +547,7 @@ check_rebuild()
 	local force_rebuild force_no_rebuild
 	local ret system_modified="0"
 
-	setup_initrd
-
-	if [[ $? -ne 0 ]]; then
-		return 1
-	fi
+	setup_initrd || return 1
 
 	force_no_rebuild=$(kdump_get_conf_val force_no_rebuild)
 	force_no_rebuild=${force_no_rebuild:-0}
@@ -761,8 +746,7 @@ check_and_wait_network_ready()
 
 		# if server removes the authorized_keys or, no /root/.ssh/kdump_id_rsa
 		ddebug "$errmsg"
-		echo "$errmsg" | grep -q "Permission denied\|No such file or directory\|Host key verification failed"
-		if [[ $? -eq 0 ]]; then
+		if echo "$errmsg" | grep -q "Permission denied\|No such file or directory\|Host key verification failed"; then
 			derror "Could not create $DUMP_TARGET:$SAVE_PATH, you probably need to run \"kdumpctl propagate\""
 			return 1
 		fi
@@ -788,16 +772,11 @@ check_and_wait_network_ready()
 check_ssh_target()
 {
 	check_and_wait_network_ready
-	if [[ $? -ne 0 ]]; then
-		return 1
-	fi
-	return 0
 }
 
 propagate_ssh_key()
 {
-	check_ssh_config
-	if [[ $? -ne 0 ]]; then
+	if ! check_ssh_config; then
 		derror "No ssh config specified in $KDUMP_CONFIG_FILE.  Can't propagate"
 		exit 1
 	fi
@@ -904,8 +883,7 @@ local_fs_dump_target()
 {
 	local _target
 
-	_target=$(grep -E "^ext[234]|^xfs|^btrfs|^minix" /etc/kdump.conf)
-	if [[ $? -eq 0 ]]; then
+	if _target=$(grep -E "^ext[234]|^xfs|^btrfs|^minix" /etc/kdump.conf); then
 		echo "$_target" | awk '{print $2}'
 	fi
 }
@@ -967,8 +945,7 @@ check_fence_kdump_config()
 			return 1
 		fi
 		# node can be ipaddr
-		echo "$ipaddrs " | grep -q "$node "
-		if [[ $? -eq 0 ]]; then
+		if echo "$ipaddrs " | grep -q "$node "; then
 			derror "Option fence_kdump_nodes cannot contain $node"
 			return 1
 		fi
@@ -1062,14 +1039,12 @@ check_final_action_config()
 
 start()
 {
-	check_dump_feasibility
-	if [[ $? -ne 0 ]]; then
+	if ! check_dump_feasibility; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
 
-	check_config
-	if [[ $? -ne 0 ]]; then
+	if ! check_config; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
@@ -1078,14 +1053,12 @@ start()
 		selinux_relabel
 	fi
 
-	save_raw
-	if [[ $? -ne 0 ]]; then
+	if ! save_raw; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
 
-	check_current_status
-	if [[ $? == 0 ]]; then
+	if check_current_status; then
 		dwarn "Kdump already running: [WARNING]"
 		return 0
 	fi
@@ -1097,14 +1070,12 @@ start()
 		fi
 	fi
 
-	check_rebuild
-	if [[ $? != 0 ]]; then
+	if ! check_rebuild; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
 
-	start_dump
-	if [[ $? != 0 ]]; then
+	if ! start_dump; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
@@ -1114,8 +1085,7 @@ start()
 
 reload()
 {
-	check_current_status
-	if [[ $? -ne 0 ]]; then
+	if ! check_current_status; then
 		dwarn "Kdump was not running: [WARNING]"
 	fi
 
@@ -1123,24 +1093,20 @@ reload()
 		reload_fadump
 		return $?
 	else
-		stop_kdump
-	fi
-
-	if [[ $? -ne 0 ]]; then
-		derror "Stopping kdump: [FAILED]"
-		return 1
+		if ! stop_kdump; then
+			derror "Stopping kdump: [FAILED]"
+			return 1
+		fi
 	fi
 
 	dinfo "Stopping kdump: [OK]"
 
-	setup_initrd
-	if [[ $? -ne 0 ]]; then
+	if ! setup_initrd; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
 
-	start_dump
-	if [[ $? -ne 0 ]]; then
+	if ! start_dump; then
 		derror "Starting kdump: [FAILED]"
 		return 1
 	fi
@@ -1168,6 +1134,7 @@ stop_kdump()
 		$KEXEC -p -u
 	fi
 
+	# shellcheck disable=SC2181
 	if [[ $? != 0 ]]; then
 		derror "kexec: failed to unload kdump kernel"
 		return 1
@@ -1179,16 +1146,14 @@ stop_kdump()
 
 reload_fadump()
 {
-	echo 1 > $FADUMP_REGISTER_SYS_NODE
-	if [[ $? == 0 ]]; then
+	if echo 1 > $FADUMP_REGISTER_SYS_NODE; then
 		dinfo "fadump: re-registered successfully"
 		return 0
 	else
 		# FADump could fail on older kernel where re-register
 		# support is not enabled. Try stop/start from userspace
 		# to handle such scenario.
-		stop_fadump
-		if [[ $? == 0 ]]; then
+		if stop_fadump; then
 			start_fadump
 			return $?
 		fi
@@ -1205,6 +1170,7 @@ stop()
 		stop_kdump
 	fi
 
+	# shellcheck disable=SC2181
 	if [[ $? != 0 ]]; then
 		derror "Stopping kdump: [FAILED]"
 		return 1
@@ -1215,10 +1181,7 @@ stop()
 }
 
 rebuild() {
-	check_config
-	if [[ $? -ne 0 ]]; then
-		return 1
-	fi
+	check_config || return 1
 
 	if check_ssh_config; then
 		if ! check_ssh_target; then
@@ -1226,10 +1189,7 @@ rebuild() {
 		fi
 	fi
 
-	setup_initrd
-	if [[ $? -ne 0 ]]; then
-		return 1
-	fi
+	setup_initrd || return 1
 
 	dinfo "Rebuilding $TARGET_INITRD"
 	rebuild_initrd
