port raw dump from rhel6 [v7]
Resolves: bz805783

kdumpctl: save_raw if found vmcore
mkdumprd: checking available size of raw disk
dracut module: do the dumping

Note, add a dir /kdumpscripts for monitor_dd_progress and future
kdump scripts
[v1->v2]: monitor_dd_process become a script instead of a function
          add missed utils
          use pipe with dc
[v2->v3]: Don: fix dd_progress_file typo
          Vivek: move [ -f $conf_file ] earlier
                 don't split keyfile= and [ -f keyfile ]
                 move default core_collector earlier
                 move non-makedumpfile warnings to mkdumprd
                 make check available size a common function
          Amerigo: use less pipe for grep then awk print
                   use shell (( )) instead of dc
          use cut instead of awk
          no need install dc and awk
          make DD_BLKSIZE a variable
          don't add 0755 file in git, chmod in module-setup.sh
[v3->v4]: vivek: kdumpctl multi raw target handling
          monitor_dd_progress- fix wrong size calculation:
          the tail -1 of dd pregress file is in bytes instead of blocks
          only print the whole dd src file size for non-filtered case
          check [ -b raw target device ] before dump
[v4->v5]: vivek: move check [ -b $1 ] before monitor_dd_progress
          remove multi target function
[v5->v6]: vivek: only warning for raw dump of non-makedumpfile core_collector
[v6->v7]: kdumpctl should return 0 when there's no raw target

Signed-off-by: Dave Young <dyoung@redhat.com>
Acked-by: Vivek Goyal <vgoyal@redhat.com>

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -281,6 +281,41 @@ function status()
 	fi
 }
 
+function save_raw()
+{
+	local kdump_dir
+	local raw_target
+
+	raw_target=$(awk '$1 ~ /^raw$/ { print $2; }' $KDUMP_CONFIG_FILE)
+	[ -z "$raw_target" ] && return 0
+	[ -b "$raw_target" ] || {
+		echo "raw partition $raw_target not found"
+		return 1
+	}
+	kdump_dir=`grep ^path $KDUMP_CONFIG_FILE | cut -d' '  -f2-`
+	if [ -z "${kdump_dir}" ]; then
+		coredir="/var/crash/`date +"%Y-%m-%d-%H:%M"`"
+	else
+		coredir="${kdump_dir}/`date +"%Y-%m-%d-%H:%M"`"
+	fi
+
+	mkdir -p "$coredir"
+	[ -d "$coredir" ] || {
+		echo "failed to create $coredir"
+		return 1
+	}
+	if makedumpfile -R $coredir/vmcore <$raw_target >/dev/null 2>&1; then
+		# dump found
+		echo "Dump saved to $coredir/vmcore"
+		# wipe makedumpfile header
+		dd if=/dev/zero of=$raw_target bs=1b count=1 2>/dev/null
+	else
+		rm -rf "$coredir"
+	fi
+
+	return 0
+}
+
 function start()
 {
 	local nr
@@ -290,7 +325,13 @@ function start()
 		return 1
 	}
 
-	#TODO check raw partition for core dump image
+	save_raw
+	if [ $? -ne 0 ]; then
+		echo -n "Starting kdump:"; echo
+		$LOGGER "failed to start up"
+		return 1
+	fi
+
 	status 
 	rc=$?
 	if [ $rc == 2 ]; then
@@ -337,6 +378,11 @@ function stop()
 		return 1
 	fi
 }
+
+if [ ! -f "$KDUMP_CONFIG_FILE" ]; then
+	echo -n "No kdump config file found!"; echo
+	exit 1
+fi
 
 case "$1" in
   start)
