kdumpctl: for fence_kdump, the ipaddr of this node should be excluded from list
kdump should not send fence_kdump notifications to local host, because
the role of the falied node (i.e local host) is to send fence_kdump
notifications to other nodes to tell them I'm kdumping, tell to itself is
nonsense. And we have excluded hostname of local host but when one use ip
address we also need exclude it.

Signed-off-by: Pingfan Liu <piliu@redhat.com>
Reviewed-by: Xunlei Pang <xlpang@redhat.com>
Acked-by: Dave Young <dyoung@redhat.com>

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -1099,11 +1099,18 @@ check_kdump_feasibility()
 check_fence_kdump_config()
 {
 	local hostname=`hostname`
+	local ipaddrs=`hostname -I`
 	local nodes=$(get_option_value "fence_kdump_nodes")
 
 	for node in $nodes; do
 		if [ "$node" = "$hostname" ]; then
 			echo "Option fence_kdump_nodes cannot contain $hostname"
+			return 1
+		fi
+		# node can be ipaddr
+		echo $ipaddrs | grep $node > /dev/null
+		if [ $? -eq 0 ]; then
+			echo "Option fence_kdump_nodes cannot contain $node"
 			return 1
 		fi
 	done
