Resolves: bz 645734

diff --git a/mkdumprd b/mkdumprd
--- a/mkdumprd
+++ b/mkdumprd
@@ -1313,6 +1313,11 @@ case "\$1" in
             echo nameserver \$i >> /etc/resolv.conf 
         done
         ;;
+
+    *)
+        echo "Unable to get a DHCP address retry..."
+        exit 1
+        ;;
 esac
 
 exit 0
